version: '3.8'

services:
  project-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: abraham
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
