-- Create sequence if not exists
CREATE SEQUENCE IF NOT EXISTS user_id_seq INCREMENT BY 1;

-- Create user table
CREATE TABLE IF NOT EXISTS "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count_nodes BIGINT DEFAULT 0,
    password    VARCHAR(255)                            NOT NULL,
    username    VARCHAR(50)                             NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
    );

-- Add unique constraint on username
ALTER TABLE "user" ADD CONSTRAINT unique_username UNIQUE (username);

-- Create node table
CREATE TABLE IF NOT EXISTS node
(
    id      BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL,
    text    VARCHAR(255),
    user_id BIGINT       NOT NULL,
    CONSTRAINT node_pkey PRIMARY KEY (id, user_id)
    );

-- Add foreign key constraint
ALTER TABLE node
    ADD CONSTRAINT FK7fi376i6naekbnkmnf3pmchyk FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE NO ACTION;



